travis:
  secure:
    BINSTAR_TOKEN: QrHniRS3fyjMQWDuWwdcRDfMrmodDsfpFP9gIRg0CZ3Kg4htqgAPnYzVSsQyRGgeJzpR6x7oGunj3tEnUM3hzxe55X3ZPciZDrp9gVqCA9owN0Ywboql35wi7xIxZf+QcUvuTvXBy3roDWmP37BKo8fM1MPioH4YuY+rKt7jTSCBeyr6lXYeW/UrzCQUXYp+G6eNUAIUA8FOlxklGHqzyF6yvkLys+1N1aGT1x2kujdKuUFLnMLgPMGfqTjFf9TiJuukAywxS7hxnRUFxFgmfUc5L+HJ0JDjCk80c1pVz2yqhQPrgdqBQ0cln/AGHkfyXVPaqxAtRyJce8/1IlJ5u7hcv1WSAIeM8kDBfqKrcX1lowNULLHWJJL3OJDEsV7xD8pNni+t7IJtP7QwewrT4Vs68LNsTn2F141XAQVZiGJrfCFAGkC4lnvk58ZRS1im5n8AnHZH+U0ik5JJUvJLxnBjK0c19QH3yQxpbrjNjEJhG8xhu6O7ofyIViYPbRRVMsiLeNcIcEoY/g8JfgI5vGdMag0jB3PsM+WvA3LF4otMjJTm+gSq+VKxFOy6AD2Zw/gl8i2ZAahK8mtRW8LdRkY4KKdi3YwnbNCOHzz0mRtCZdAeTqRo5X0u9r5C5dcLTjlqxr8qpQi3NfVjvFnsxwj9Tde2nBdkb1PlWH6J4Po=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
